# permissions for end users to view ironcoremetalclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-ironcore-metal
    app.kubernetes.io/managed-by: kustomize
  name: ironcoremetalcluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - ironcoremetalclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - ironcoremetalclusters/status
  verbs:
  - get
