apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IroncoreMetalMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-ironcore-metal
    app.kubernetes.io/managed-by: kustomize
  name: ironcoremetalmachinetemplate-sample-control-plane
spec:
  template:
    spec:
      serverSelector:
        matchLabels:
          server: metal
      image: ghcr.io/ironcore-dev/os-images/gardenlinux:1443.3