## Append samples of your project ##
resources:
- infrastructure_v1alpha1_metalcluster.yaml
- infrastructure_v1alpha1_metalmachine.yaml
- infrastructure_v1alpha1_metalmachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
